version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: t4jn3h4slo
      MYSQL_DATABASE: rapidhcm
      MYSQL_USER: admin
      MYSQL_PASSWORD: t4jn3h4slo
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./rapid-backend:/var/www/html/app
      - /var/www/html/app/vendor
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./rapid-backend:/var/www/html/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database